#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# deploy.sh — Provision Azure resources for the "Ask Your Twin" demo
# ---------------------------------------------------------------------------
set -euo pipefail

# ---- Parameters -----------------------------------------------------------
RESOURCE_GROUP="${1:?Usage: ./deploy.sh <RESOURCE_GROUP> [LOCATION] [NAME_PREFIX]}"
LOCATION="${2:-eastus2}"
NAME_PREFIX="${3:-asktwin}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BICEP_FILE="${SCRIPT_DIR}/main.bicep"
DEMO_DIR="${SCRIPT_DIR}/../demo"

echo "============================================="
echo " Ask Your Twin — Azure Deployment"
echo "============================================="
echo "Resource Group : ${RESOURCE_GROUP}"
echo "Location       : ${LOCATION}"
echo "Name Prefix    : ${NAME_PREFIX}"
echo "Bicep template : ${BICEP_FILE}"
echo ""

# ---- 1. Resource group ----------------------------------------------------
echo "▶ Ensuring resource group '${RESOURCE_GROUP}' exists..."
az group show --name "${RESOURCE_GROUP}" --output none 2>/dev/null || \
  az group create --name "${RESOURCE_GROUP}" --location "${LOCATION}" --output none
echo "  ✔ Resource group ready."

# ---- 2. Deploy Bicep template ---------------------------------------------
echo "▶ Deploying Bicep template (this may take a few minutes)..."
DEPLOY_OUTPUT=$(az deployment group create \
  --resource-group "${RESOURCE_GROUP}" \
  --template-file "${BICEP_FILE}" \
  --parameters namePrefix="${NAME_PREFIX}" \
  --query 'properties.outputs' \
  --output json)

echo "  ✔ Deployment complete."

# ---- 3. Capture outputs ---------------------------------------------------
OPENAI_ENDPOINT=$(echo "${DEPLOY_OUTPUT}" | python3 -c "import sys,json; print(json.load(sys.stdin)['openAiEndpoint']['value'])")
OPENAI_DEPLOYMENT=$(echo "${DEPLOY_OUTPUT}" | python3 -c "import sys,json; print(json.load(sys.stdin)['openAiDeploymentName']['value'])")
SWA_NAME=$(echo "${DEPLOY_OUTPUT}" | python3 -c "import sys,json; print(json.load(sys.stdin)['staticWebAppName']['value'])")
SWA_HOSTNAME=$(echo "${DEPLOY_OUTPUT}" | python3 -c "import sys,json; print(json.load(sys.stdin)['staticWebAppDefaultHostname']['value'])")

# Derive the OpenAI account name from the endpoint
OPENAI_ACCOUNT_NAME=$(echo "${OPENAI_ENDPOINT}" | sed -E 's|https://([^.]+)\..*|\1|')

echo ""
echo "  Endpoint   : ${OPENAI_ENDPOINT}"
echo "  Deployment : ${OPENAI_DEPLOYMENT}"
echo "  SWA Name   : ${SWA_NAME}"
echo "  SWA URL    : https://${SWA_HOSTNAME}"

# ---- 4. Retrieve OpenAI API key ------------------------------------------
echo ""
echo "▶ Retrieving Azure OpenAI API key..."
OPENAI_API_KEY=$(az cognitiveservices account keys list \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${OPENAI_ACCOUNT_NAME}" \
  --query 'key1' \
  --output tsv)
echo "  ✔ API key retrieved."

# ---- 5. Configure Static Web App settings ---------------------------------
echo "▶ Setting app settings on Static Web App..."
az staticwebapp appsettings set \
  --name "${SWA_NAME}" \
  --resource-group "${RESOURCE_GROUP}" \
  --setting-names \
    "AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}" \
    "AZURE_OPENAI_API_KEY=${OPENAI_API_KEY}" \
    "AZURE_OPENAI_DEPLOYMENT=${OPENAI_DEPLOYMENT}" \
  --output none
echo "  ✔ App settings configured."

# ---- 6. Generate local .env.local ----------------------------------------
ENV_FILE="${DEMO_DIR}/.env.local"
echo "▶ Writing local dev config to ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_API_KEY=${OPENAI_API_KEY}
AZURE_OPENAI_DEPLOYMENT=${OPENAI_DEPLOYMENT}
EOF
echo "  ✔ .env.local written."

# ---- Done -----------------------------------------------------------------
echo ""
echo "============================================="
echo " ✅  Deployment complete!"
echo "============================================="
echo ""
echo " Static Web App URL : https://${SWA_HOSTNAME}"
echo " OpenAI Endpoint    : ${OPENAI_ENDPOINT}"
echo " Model Deployment   : ${OPENAI_DEPLOYMENT}"
echo ""
echo " Local dev config written to demo/.env.local"
echo " Run 'cd demo && npm run dev' to start locally."
echo ""
